[book]
authors = ["Ankitects Pty Ltd and contributors"]
language = "en"
multilingual = false
src = "src"
title = "Anki Manual"

[build]
create-missing = true

[output.html]
git-repository-url = "https://github.com/ankitects/anki-manual/"
cname = "docs.ankiweb.net"

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
